"""Defaults for the adaptation methods included in this release."""

import math


entropy_margin = 0.4 * math.log(1000)

algorithm_defaults = {
    "no_adaptation": {"model_selection_method": "last_iterate"},
    "tent": {"optimizer": "SGD"},
    "sar": {
        "optimizer": "SGD",
        "sar_margin_e0": entropy_margin,
        "reset_constant_em": 0.2,
    },
    "sar2": {
        "optimizer": "SGD",
        "sar_margin_e0": entropy_margin,
        "reset_constant_em": 0.2,
        "alpha": 1e3,
        "beta": 50,
        "feature_bank_momentum": 0.9,
    },
    "cotta": {
        "optimizer": "SGD",
        "alpha_teacher": 0.999,
        "restore_prob": 0.01,
        "threshold_cotta": 0.92,
        "aug_size": 32,
        "cotta_loss": "teacher_ce",
    },
    "nctta": {
        "optimizer": "SGD",
        "thre_ent": entropy_margin,
        "margin_ent": entropy_margin,
        "reweight_ent": 1.0,
        "nu": 5.0,
        "eta": 1.0,
        "scale": 5.0,
        "top_k": 10,
        "mix_prob_weight": 0.3,
    },
    "come": {"optimizer": "SGD", "K": 1000},
    "adadem": {
        "optimizer": "SGD",
        "adadem_pi": 0.1,
        "adadem_mode": "adadem",
    },
    "adainit": {
        "optimizer": "SGD",
        "adainit_backend": "nctta",
        "adadem_pi": 0.1,
        "adadem_mode": "adadem",
        "thre_ent": entropy_margin,
        "margin_ent": entropy_margin,
        "reweight_ent": 1.0,
        "nu": 5.0,
        "eta": 1.0,
        "scale": 5.0,
        "top_k": 10,
        "mix_prob_weight": 0.3,
        "sar_margin_e0": entropy_margin,
        "reset_constant_em": 0.2,
        "adainit_signature_momentum": 0.95,
        "adainit_signature_window_size": 1,
        "adainit_require_full_signature_window": False,
        "adainit_signature_distance": "standardized",
        "adainit_detector_distance": "same",
        "adainit_detector_signature_source": "instantaneous",
        "adainit_score_momentum": 0.95,
        "adainit_drift_beta": 3.0,
        "adainit_fixed_drift_threshold": 0.1,
        "adainit_drift_min_ratio": 2.0,
        "adainit_eps": 1e-6,
        "adainit_min_reference_samples": 32,
        "adainit_drift_confirmations": 6,
        "adainit_detector_mode": "adaptive",
        "adainit_periodic_interval": 512,
        "adainit_periodic_include_source": False,
        "adainit_trigger_cooldown": 32,
        "adainit_cache_size": 16,
        "adainit_cache_eviction": "signature",
        "adainit_cache_admission": "mds_stable",
        "adainit_knowledge_fingerprint": "disabled",
        "adainit_fingerprint_window": 32,
        "adainit_fingerprint_magnitude_weight": 0.0,
        "adainit_cache_insert_interval": 32,
        "adainit_cache_signature_source": "mds",
        "adainit_cache_min_segment_samples": 32,
        "adainit_cache_on_detection": False,
        "adainit_cache_optimizer_state": False,
        "adainit_cache_health_mode": "disabled",
        "adainit_cache_health_min_information": 0.0,
        "adainit_cache_health_max_concentration": 1.0,
        "adainit_cache_health_min_update_cosine": -1.0,
        "adainit_cache_health_min_fingerprint_norm": 0.0,
        "adainit_cache_health_update_weight": 0.0,
        "adainit_history_retrieval": "signature",
        "adainit_history_fingerprint_max_distance": -1.0,
        "adainit_history_fingerprint_max_ratio": -1.0,
        "adainit_max_history_candidates": 1,
        "adainit_history_min_age": 64,
        "adainit_history_match_ratio": -1.0,
        "adainit_history_max_distance": 0.05,
        "adainit_history_radius_multiplier": 3.0,
        "adainit_source_for_unseen_only": False,
        "adainit_source_min_drift_ratio": 15.0,
        "adainit_source_min_current_entropy": 3.8,
        "adainit_history_score_bonus": 0.0,
        "adainit_history_min_drift_ratio": 0.0,
        "adainit_context_diversity_weight": 0.0,
        "adainit_history_max_entropy_increase": 0.0,
        "adainit_periodic_selection_margin": 0.02,
        "adainit_periodic_history_max_entropy_increase": 0.0,
        "adainit_prefer_matched_history": False,
        "adainit_num_views": 8,
        "adainit_selection_window": 4,
        "adainit_counterfactual_steps": 1,
        "adainit_counterfactual_batch_source": "current",
        "adainit_candidate_eval_batch_size": 0,
        "adainit_audit_candidate_accuracy": False,
        "adainit_initialization_selector": "sequential_view_evidence",
        "adainit_evidence_horizon": 32,
        "adainit_evidence_min_samples": 4,
        "adainit_evidence_max_samples": 64,
        "adainit_evidence_confidence_scale": 1.0,
        "adainit_evidence_warmup": 0,
        "adainit_evidence_timing": "prequential",
        "adainit_sequential_score": "entropy",
        "adainit_sequential_view_jsd_weight": 0.0,
        "adainit_sequential_context_weight": 0.0,
        "adainit_oracle_horizon": 0,
        "adainit_oracle_max_history_candidates": 0,
        "adainit_oracle_include_source": True,
        "adainit_oracle_min_accuracy_gain": 0.0,
        "adainit_oracle_log_surrogates": False,
        "adainit_oracle_log_future_view_surrogates": False,
        "adainit_native_anchor": False,
        "adainit_native_anchor_selection_margin": 0.02,
        "adainit_selection_margin": 0.0,
        "adainit_source_selection_margin": 0.05,
        "adainit_reset_current_optimizer": False,
        "adainit_max_marginal_entropy_increase": -1.0,
        "adainit_recovery_score": "post_entropy",
        "adainit_candidate_mode": "full",
    },
}
